stages:
  - build
  - test
  - deploy

# This is run by the shared GitLab runner
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - local
  script:
    - docker build -t flaskapp .

test:
  stage: test
  image: python:3.11
  tags:
    - local
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - export PYTHONPATH=$(pwd)
    - pytest tests/

deploy:
  stage: deploy
  tags:
    - local
  script:
    - echo "Deploying using local Docker"
    - docker stop flaskapp || true
    - docker rm flaskapp || true
    - docker run -d -p 5001:5000 --name flaskapp flaskapp
