#pipeline set up, tests server is working 
stages:
  - build 
  - test
  - deploy

build:
  stage: build
  image: python:3.11  
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    expire_in: 1 hour
  
test:
  stage: test
  image: python:3.11
  dependencies:
    - build
  script:
    - source venv/bin/activate
    - export PYTHONPATH=$(pwd)
    - pytest tests/

deploy:
  stage: deploy
  script:
    - source venv/bin/activate
    - cd /builds/VANESSAMEDINAUNR/cs333fp
    - git pull main
    - systemctl restart flaskapp
