stages:
  - build 
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t flaskapp .

test:
  stage: test
  image: python:3.11
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - export PYTHONPATH=$(pwd)
    - pytest tests/

deploy:
  stage: deploy
  tags:
    - local 
  script:
    - docker stop flaskapp || true
    - docker rm flaskapp || true
    - docker run -d -p 5001:5000 --name flaskapp flaskapp